# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 22:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.IntegerField(db_column=b'ID', primary_key=True, serialize=False)),
                ('category', models.TextField(blank=True, db_column=b'Category', null=True)),
                ('name', models.TextField(blank=True, db_column=b'Name', null=True)),
                ('imageurl', models.TextField(blank=True, db_column=b'ImageURL', null=True)),
                ('shortdesc', models.TextField(blank=True, db_column=b'ShortDesc', null=True)),
                ('recommended_length_of_visit', models.TextField(blank=True, db_column=b'Recommended_length_of_visit', null=True)),
                ('rate', models.FloatField(blank=True, db_column=b'Rate', null=True)),
                ('geocode', models.TextField(blank=True, db_column=b'Geocode', null=True)),
                ('address', models.TextField(blank=True, db_column=b'Address', null=True)),
                ('lat', models.TextField(blank=True, db_column=b'Lat', null=True)),
                ('lng', models.TextField(blank=True, db_column=b'Lng', null=True)),
                ('url', models.TextField(blank=True, db_column=b'URL', null=True)),
                ('longdesc', models.TextField(blank=True, db_column=b'LongDesc', null=True)),
                ('cost', models.FloatField(blank=True, db_column=b'Cost', null=True)),
            ],
            options={
                'db_table': 'Attractions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InputTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=20)),
                ('date', models.IntegerField(blank=True)),
                ('dow', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startstreet1', models.CharField(max_length=50)),
                ('startstreet2', models.CharField(max_length=50)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('interest', models.CharField(blank=True, max_length=25)),
                ('budget', models.CharField(blank=True, max_length=25)),
                ('groupsize', models.PositiveIntegerField(blank=True)),
                ('morningstarttime', models.TimeField(blank=True)),
                ('lunchstarttime', models.TimeField(blank=True)),
                ('afternoonstarttime', models.TimeField(blank=True)),
                ('morningendtime', models.TimeField(blank=True)),
                ('lunchendtime', models.TimeField(blank=True)),
                ('afternoonendtime', models.TimeField(blank=True)),
                ('morningduration', models.DecimalField(blank=True, decimal_places=3, max_digits=3)),
                ('lunchduration', models.DecimalField(blank=True, decimal_places=3, max_digits=3)),
                ('afternoonduration', models.DecimalField(blank=True, decimal_places=3, max_digits=3)),
                ('afternoonattr', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='afternoonattr', to='planner.Attractions')),
                ('lunch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='planner.Attractions')),
                ('morningattr', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='morningattr', to='planner.Attractions')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20)),
                ('update_time', models.DateTimeField(blank=True)),
                ('email', models.CharField(blank=True, max_length=32)),
                ('plans', models.ManyToManyField(to='planner.Plan')),
            ],
        ),
    ]
