# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('imageurl', models.CharField(max_length=256)),
                ('shortdesc', models.CharField(max_length=256)),
                ('longdesc', models.CharField(max_length=256)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('weburl', models.CharField(max_length=256)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20)),
                ('rectime', models.DecimalField(blank=True, decimal_places=3, max_digits=3)),
                ('mintime', models.DecimalField(blank=True, decimal_places=3, max_digits=3)),
                ('monopentime', models.TimeField()),
                ('tueopentime', models.TimeField()),
                ('wedopentime', models.TimeField()),
                ('thuopentime', models.TimeField()),
                ('friopentime', models.TimeField()),
                ('satopentime', models.TimeField()),
                ('sunopentime', models.TimeField()),
                ('monclosetime', models.TimeField()),
                ('tueclosetime', models.TimeField()),
                ('wedclosetime', models.TimeField()),
                ('thuclosetime', models.TimeField()),
                ('friclosetime', models.TimeField()),
                ('satclosetime', models.TimeField()),
                ('sunclosetime', models.TimeField()),
                ('blackoutdate', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startstreet1', models.CharField(max_length=50)),
                ('startstreet2', models.CharField(max_length=50)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('interest', models.CharField(blank=True, max_length=25)),
                ('budget', models.CharField(blank=True, max_length=25)),
                ('isstudent', models.CharField(blank=True, max_length=25)),
                ('transportation', models.CharField(blank=True, max_length=25)),
                ('groupsize', models.PositiveIntegerField(blank=True)),
                ('morningstarttime', models.TimeField(blank=True)),
                ('lunchstarttime', models.TimeField(blank=True)),
                ('afternoonstarttime', models.TimeField(blank=True)),
                ('morningendtime', models.TimeField(blank=True)),
                ('lunchendtime', models.TimeField(blank=True)),
                ('afternoonendtime', models.TimeField(blank=True)),
                ('morningduration', models.DecimalField(blank=True, decimal_places=3, max_digits=3)),
                ('lunchduration', models.DecimalField(blank=True, decimal_places=3, max_digits=3)),
                ('afternoonduration', models.DecimalField(blank=True, decimal_places=3, max_digits=3)),
                ('tb1time', models.DecimalField(blank=True, decimal_places=3, max_digits=3)),
                ('tb2time', models.DecimalField(blank=True, decimal_places=3, max_digits=3)),
                ('tb3time', models.DecimalField(blank=True, decimal_places=3, max_digits=3)),
                ('tb4time', models.DecimalField(blank=True, decimal_places=3, max_digits=3)),
                ('tb1url', models.CharField(blank=True, max_length=600)),
                ('tb2url', models.CharField(blank=True, max_length=600)),
                ('tb3url', models.CharField(blank=True, max_length=600)),
                ('tb4url', models.CharField(blank=True, max_length=600)),
                ('afternoonattr', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='afternoonattr', to='planner.Attraction')),
                ('lunch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='planner.Attraction')),
                ('morningattr', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='morningattr', to='planner.Attraction')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20)),
                ('update_time', models.DateTimeField(blank=True)),
                ('email', models.CharField(blank=True, max_length=32)),
                ('plans', models.ManyToManyField(to='planner.Plan')),
            ],
        ),
    ]
