# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='update_time',
        ),
    ]
